language: php
php:
  - 5.6
  - 5.5

before_script:
  - composer install --dev

script:
  - mkdir -p build/logs
  - cd tests
  - phpunit --coverage-clover ../build/logs/clover.xml .
  - cd ../

after_script:
  - php vendor/bin/coveralls